### ISSUE TITLE
Suchfelder: X-Button sichtbar bleiben

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#15]
Bei den Suchfeldern verschwindet der X-Button derzeit wenn man anfängt zu scrollen.
Es wäre gut wenn der immer da bleibt, dass man, wenn man sich umentscheidet, den Suchbegriff einfach weg-X-en kann.

**Comment by mrWinston** [comment]
The X always appears when the focus in in the search field. Maybe thats  okay, maybe not. I wouldn't care about that too much right now

**Comment by SayAntiAnti** [comment]
Ja, das hat nicht oberste Prio.
