### ISSUE TITLE
Fragen entdecken: Bubble Farbe

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#16]
Bubble wird wenn sie nach links aus dem Bildschirm geschoben wird nicht rot sondern bleibt grau.
Bubble ist nur auf der X-Achse schiebbar.

**Comment by ThyMYthOS** [comment]
Ist das eine Feststellung oder sollte es so sein?

**Comment by SayAntiAnti** [comment]
Soll so sein, wie oben beschrieben.
Gerade wird sie ja noch rot und lässt sich auch auf der Y-Achse bewegen.

**Comment by ThyMYthOS** [comment]
More details in #28
