### ISSUE TITLE
Burger Menu: "Home"

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#17]
"Home-Button" 
Braucht man den hier? Ein Tip in den ausgegrauten Bereich bringt einen ja auch zurück, oder?

"Profil-Einstellungen" umbennen in "Passwort"

Im Burger Menu fehlt:
FAQ (kommen noch)
+me Kodex (kommen noch)
Hilfe - darunter zu finden einmal "Bug Support" und einmal "generelle Fragen"

**Comment by ThyMYthOS** [comment]
Braucht man nicht, kann ich entfernen.
Zu den Dingen die Fehlen bitte jeweils ein extra Issue aufmachen.
