### ISSUE TITLE
Anmeldung

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#19]
Alex: Das Anmelden ging nicht reibungslos. Zuerst ging wieder nix und plötzlich war ich angemeldet. Ich kann allerdings nicht mehr nachvollziehen wie es geklappt hat.
Hier wäre bestimmt eine Info gut „du bist erfolgreich angemeldet“ oder ähnliches.
@ThyMYthOS

**Comment by CameliaKollo** [comment]
Konto anlegen geht bei mir auch nicht. 
Todo: Robot Test steht hier noch 
Nutzungsbedingungen und Datenschutzrichtlinien einfügen bzw. verlinken
Anmeldung läuft in einem Zug? Nicht über E-Mail Bestätigung?

**Comment by CameliaKollo** [comment]
Ich komm nicht rein

**Comment by mrWinston** [comment]
Könnt ihr bitte bitte bitte mehr Infos geben? Android oder iOS? Was heißt "ich komm nicht rein" genau? Was hat Alex gemacht damit er sich abmelden konnte?

**Comment by CameliaKollo** [comment]
iOS und wenn ich meine Angaben eingebe, funktioniert im Anschluss der Button mit jetzt Konto anlegen nicht. Also es passiert nichts, wenn ich draufklicke

**Comment by CameliaKollo** [comment]
Bitte jetzt bei jetzt Konto anlegen, noch groß schreiben

**Comment by mrWinston** [comment]
Registering probably doesn't work because of that: 
from src/providers/user-service/user-service.ts:32
```
    const headers = new Headers({ 'Content-Type': 'application/json'});
    const options = new RequestOptions({ headers: headers });
    var toSend = {
      username: username,
      email: email,
      password: password,
      sex: sex,
      birthYear: birthYear,
      plz: plz
    };
```
The backend doc requires the user object to be in the following format:

```
User:
{
  "id": 4,  # Integer Value, READ_ONLY
  "email": "juergen@test.de", # String, not_required
  "username": "jürgen",  # String, required, 
  "first_name": "", # String, not_required,
  "last_name": "", # String, not_required
  "reputation": 124, # Integer Value, READ_ONLY
  "zip_code": "", # String value, not_required
  "year_of_birth": null, # Integer Value, not_required
  "gender": "", #String Value, not_required
  "password": "SecretSecret" # String, WRITE_ONLY
}
```
