### ISSUE TITLE
Shipen der Fragen

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#22]
Alex: Das wischen der Fragen als gute Frage funktioniert nicht. Nur durch mehrmaliges tippe auf gute Frage wird die Frage zu +me (und grün)

**Comment by mrWinston** [comment]
When swiping to the right, there is no post request to /upvote sent. However, when I downvote a question, it works as expected

**Comment by ThyMYthOS** [comment]
Fixed with 0e496ee9ffe939296cb6d1bd0845e96f01e69206
