### ISSUE TITLE
Outlines der Icons, Home-Screen (iOS)

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#23]
Auf dem Home-Screen bekommen die Icons auf meinem iPhone 5s ziemlich harte Outlines.

![img_2488](https://user-images.githubusercontent.com/30910570/29446963-96faf3d2-83ef-11e7-96ac-162bbffc1003.PNG)

**Comment by ThyMYthOS** [comment]
Scheint ein reines iOS-Problem zu sein. Normal sollte die Outline leicht grün sein. Evtl. versteht iOS was im SVG nicht?

**Comment by SayAntiAnti** [comment]
Das kann gut sein. Bei Simons Bruder unter Android sah das auch richtig aus.
Wie könnten wir das lösen? Brauchst du die Icons in einem anderen Dateiformat?
