### ISSUE TITLE
Hashtag Suche: Tags dürfen nur noch ausgewählt werden

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#24]
Wenn ich in der suche einen Hashtag eingebe werden mir ganz richtig die entsprechenden fragen angezeigt. Wenn ich den Hashtag dann oben in der Suchzeile wieder rauslösche, löscht sich unten in der Auswahlliste ebenfalls die Tag-Beschriftung raus.
(Siehe Screenshot: hier am Beispiel des Tags "Demokratie")
Wenn ich in das Suchfeld dann etwas Anderes schreibe taucht das in Echtzeit unten anstelle des Tags Demokratie auf.

(iPhone 5s)

![img_2496](https://user-images.githubusercontent.com/30910570/29446984-b82cb5a4-83ef-11e7-9071-b96a27da7c1d.PNG)

**Comment by simongogolin** [comment]
@ThyMYthOS 
Wie du oben auf dem Screenshot sehen kannst wird das Suchfeld unter iOS nur ganz zart hellgrün dargestellt, anstatt weiß.
Und ich habe das Problem, dass ich die Tastatur nicht manuell ausblenden kann, was leider sehr stört. Ich muss dann erst eine Frage antippen und dann wieder zurück in die Liste gehen, damit ich die Tastatur wegbekomme.
Unter iOS ist man es meistens gewöhnt, die Tastatur einfach mit einem wisch nach unten aus dem Bildschirm schieben zu können. Wäre das bei uns evtl. auch möglich?

**Comment by ThyMYthOS** [comment]
Bitte in drei Issues aufteilen:
1) Farbe sollte kein Problem sein
2) Überschreiben der Tags ist ein Bug. Das Selektieren der Tags muss ich aber sowieso grundlegend überarbeiten.
3) Was die Tastatur angeht, hab ich leider kein Testgerät. Das könnte schwierig werden.

**Comment by AVWG** [comment]
@ThyMYthOS 

evtl. einfacher:

Tags dürfen nicht eingegeben sondern nur aus der Liste der Tags ausgewählt werden. Tastatur und Folgeprobleme werden damit vermieden.
