### ISSUE TITLE
Mit einem swipe am rechten Bildschirmrand öffnet sich das Menü.

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#26]
@ThyMYthOS 
Mit einem swipe am rechten Bildschirmrand kann ich derzeit das Menü öffnen.
Vielleicht hängt das mit dem ein oder anderen Problem mit den swipe-bewertungen zusammen... Kannst du das ausstellen?

(iPhone 5s)

**Comment by ThyMYthOS** [comment]
Ja, kann ich ausstellen. War aber bisher Absicht.

**Comment by simongogolin** [comment]
Ok. Wäre super, wenn du das rausnehmen könntest. Ich glaube es ist am Ende verwirrend für die Nutzer, wenn die Swipe-Geste für verschiedene Aktionen auslösen kann.

**Comment by ThyMYthOS** [comment]
Fixed with 0100cdc1556e.
