### ISSUE TITLE
Screen: Fragen entdecken

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#28]
@ThyMYthOS 
Beim Bewerten per shipe gibt es auf dem iPhone 5s das Problem, dass vermutlich wieder der Bildschirm zu klein ist ... Um weit genug zu swipen muss ich mir schon etas mühe geben. Sonst taucht die selbe Frage gleich wieder auf.
Oder täuscht das vielleicht, weil viele Fragen doppelt auftauchen?

Derzeit ist ja auch noch nicht die richtige Animation drin. Brauchst du nochmal Input, für die echte Animation? bzw. Kannst du mit dem Code, den @Bartz0210 dir geschickt hat arbeiten?

![img_2501](https://user-images.githubusercontent.com/30910570/29447373-df0e7188-83f1-11e7-8306-a27eae69a0e1.PNG)

**Comment by simongogolin** [comment]
Anstellle des Avatar-Icon rechts müsste ebenfalls das +me-Icon stehen, wie es im Bereich Fragen suchen der fall ist.

**Comment by mrWinston** [comment]
Probably related to #22

**Comment by ThyMYthOS** [comment]
Soll das genauso aussehen, wie im "Fragen Suchen", wenn man dort eine Frage bewertet? Oder soll es nach wie vor möglich sein, die ganze Bubble zu verschieben?

**Comment by simongogolin** [comment]
Das Bewerten der Bubbles soll bei "Fragen entdecken" so aublaufen:
Bei einem Swipe nach rechts (positiv) soll die "Nase" der Bubble nach rechts wandern während sich die Farbe nach grün verändert. Ansonsten bleibt die Bubble statisch. @Bartz0210 Tim meinte er hätte dir dazu einen Code geschickt? Ich hab dir dazu unten einen Mini-Film zur Ansicht angehängt, das auch zeigt was mit den weiteren Elementen so passieren soll. (Das Video ist leider verzerrt, wir haben da gerade auf die schnelle was beim Rendern versemmelt, aber ich glaube es ist ausreichen um zu sehen was passieren soll)
Bei einem Swipe nach links (negativ) soll die Bubble in ihrem default-state nach links aus dem Bildschirm geschoben werden. Auch dieser Fall ist im Video zu sehen.

[Komp 1_4.mov.zip](https://github.com/wepublic/ionic-app/files/1235641/Komp.1_4.mov.zip)

**Comment by simongogolin** [comment]
Bei "Fragen suchen" so es so ablaufen (ich weiß nicht ob du das jetzt bereits so umgesetzt hast, weil ich mich leider nicht mehr in der App einloggen kann ... ):
Genau wie bei "Fragen entdecken" soll bei "Fragen suchen" der swipe nach rechts (positiv) die "Nase" der Bubble nach rechts schieben, während sich die Farbe nach grün verändert. Ansonsten bleibt die Bubble statisch. Der gelbe Community-Avatar und die Zahl die auf der linken Seite stehen sollen auf 0% sichbarkeit verblassen – gleiches gilt für den grünen verlauf auf der rechten Seite, auf dem "gute Frage" und das große "+" zu sehen ist.
Während sich die Nase der Bubble also nach rechts verschiebt, und die Icons verblassen sollte auf der linken seite das "+me" Avatar-Icon und die gelbe Zahl eingeblendet werden.

Bei einem Swipe nach links soll sich die Bubble ohne eine Farbveränderung (wie bei dem Oben mitgeschickten Video) nach links aus dem Bildschirm herausschieben. Das gelbe Community-Avatar-Icon, die Zahl die auf der linken Seite und der grüne Balken "gute Frage" und das große "+" auf der rechten Seite soll währenddessen auf 0% Sichtbarkeit verblassen.
Wenn dies geschehen ist, sollten die weiter unten folgenden Bubbles nach oben aufrutschen um die entstandene Lücke in der Liste zu schließen.

Ich hoffe, das ist einigermaßen verständlich ... und auch machbar ... Wir können dazu auch gerne nochmal telefonieren ... +176 261 33 33 1

**Comment by CameliaKollo** [comment]
Bei mir geht das rausschieben, also das nicht interessant finden von Fragen nicht auf dem iPhone5s 
Ich sehe auch keine Icons.

**Comment by ThyMYthOS** [comment]
Fixed with 7283434a7
