### ISSUE TITLE
Schatten

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#29]
@ThyMYthOS 
Im Screendesign hatten die Bubbles, die "x Antworten" Lables und vor allem die Navigations- und Titel-leiste feine Schatten um die besser voneinander abzusetzen und um Flimmern zu verhindern.
Ich weiß jetzt natürlich nicht wie aufwendig das ist. Wäre es möglich die Schatten noch mit reinzubringen? Bzw. Wenn das auch nur bei der Titel- und Navigationsleiste funktionieren würde wäre ich schon sehr glücklich!

[step1.pdf](https://github.com/wepublic/ionic-app/files/1233528/step1.pdf)

**Comment by ThyMYthOS** [comment]
Ich seh in dem PDF keine Schatten.

**Comment by simongogolin** [comment]
Zugegeben, die Schatten sind recht dezent. Aber helfen letzlich dann doch dabei dass es insgesamt rund aussieht. Ich hänge unten ein paar gezoomte Screenshots aus dem PDF an.
Wie gesagt, ich weiß nicht wie viel aufwand das für dich bedeuten würde.
– Mit einem kleiner Schatten unter der Titel-Leiste und evtl. der Navigationsleiste wäre ich aber auch schon sehr glücklich.

<img width="1266" alt="bildschirmfoto 2017-08-18 um 21 03 31" src="https://user-images.githubusercontent.com/30910570/29473694-fd65cdae-8458-11e7-8d52-b03ad4c1f064.png">
<img width="508" alt="bildschirmfoto 2017-08-18 um 21 04 03" src="https://user-images.githubusercontent.com/30910570/29473695-fd791896-8458-11e7-878e-e95ff9007722.png">
<img width="501" alt="bildschirmfoto 2017-08-18 um 21 04 25" src="https://user-images.githubusercontent.com/30910570/29473696-fd87a08c-8458-11e7-95e0-b2e23f3c334d.png">
<img width="724" alt="bildschirmfoto 2017-08-18 um 21 05 15" src="https://user-images.githubusercontent.com/30910570/29473697-fd9542a0-8458-11e7-9b95-d66258202b3b.png">

**Comment by ThyMYthOS** [comment]
Der Schatten für die Lasche wird schwierig. Bei der Navigations- und Titelleiste scheint es Unterschiede zwischen iOS und Android zu geben. Außerdem macht es scheinbar einen Unterschied, ob der Seiteninhalt scrollbar ist.

**Comment by simongogolin** [comment]
Ok. Dann würde ich dass auch erst einmal hinten anstellen. Du wirst ja mit der Swipe-Animation der Bubbles noch genügend zu tun haben, fürchte ich.

**Comment by ThyMYthOS** [comment]
So hab ich es hinbekommen. Ist das erst mal OK?
![schatten](https://user-images.githubusercontent.com/4992400/29506943-49e2c500-864e-11e7-9ff7-4c71722d559d.png)

**Comment by ThyMYthOS** [comment]
Und hier das Eingabefeld:
![select](https://user-images.githubusercontent.com/4992400/29507757-c17a4dba-8651-11e7-9b05-75ca42587dcf.png)
