### ISSUE TITLE
Getting lost in the menu

### ISSUE THREAD

**Issue by SayAntiAnti** [wepublic/ionic-app#32]
Simon: In der aktuellen Version der App geht man unter iOS im Menü verloren. Ich habe auf Profil-Einstellungen getippt und hatte daraufhin keine Möglichkeit mehr auf den Home-Screen der App zu gelangen. Hier fehlt leider einfach ein Zurück-Button. #

**Comment by ThyMYthOS** [comment]
This is related to #13. The menu has to be defined inside the tab page.
