### ISSUE TITLE
Aktualisierung der Datenschutzrichtlinie für Offline-Anzeige

### ISSUE THREAD

**Issue by SayAntiAnti** [wepublic/ionic-app#33]
Neue Datenschutzrichtline siehe unten:

**Comment by SayAntiAnti** [comment]
Simon: Nachdem ich mich nicht mehr mit meinem account anmelden konnte, wollte ich einen neuen account anlegen.
Habe dafür eine andere Mailadresse eingegeben und alles ausgefüllt. Leider führt der Konto-Anlegen-Button nur auf folgende Seite (siehe screenshot unten), von der aus ich nicht weiter kommen.

![img_2515](https://user-images.githubusercontent.com/30910528/29476664-5720f2fe-8465-11e7-8407-133ecbc23926.PNG)

**Comment by simongogolin** [comment]
Bei Julia Tritt exakt der selbe Fehler auf.

**Comment by CameliaKollo** [comment]
Bei mir auch. 
Die Nutzungsbedingungen und Datenschutzrichtlinien müssten mit der Anmeldung einmal angeklickt werden können, damit wir auch sichergehen, dass sie jeder gesehen hat.

Der Nutzer muss schon vor Beginn der Datenverwendung die Möglichkeit haben, die Datenschutzerklärung einzusehen. Um diese Pflicht zu erfüllen gibt es drei Möglichkeiten:

    Bereitstellung der Datenschutzerklärung im App-Store,
    Unterrichtung nach dem Herunterladen oder
    unmittelbar vor dem ersten Start der App.

**Comment by ThyMYthOS** [comment]
Der letzte iOS-Build hat vermutlich die falsche Backend-URL.

**Comment by simongogolin** [comment]
Gibt es dafür einen einfachen Weg das zu beheben?

**Comment by ThyMYthOS** [comment]
Ne, muss man neu bauen.

**Comment by simongogolin** [comment]
Anmeldung unter iOS funktioniert bei mir jetzt wieder.
Julia hat das Problem allerdings noch ...

**Comment by ThyMYthOS** [comment]
Noch kein Update gemacht?

**Comment by CameliaKollo** [comment]
OK update zu den Datenschutzrichtlinien. Alles soweit richtig, auch ohne anklicken. Leider ist aber eine Verlinkung auf die Website nicht ausreichend, wenn die App offline funktionert. Daher Änderungen zum bisherigen Text:

Datenschutzrichtlinie
Die Betreiber dieser App nehmen den Schutz deiner persönlichen Daten sehr ernst. Wir behandeln deine personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. Damit du dich bei der Nutzung unserer App sicher fühlst, möchten wir dich hier zusätzlich zu den gesetzlichen Bestimmungen darüber informieren, welche Daten wir erheben und wie wir diese verarbeiten und nutzen.
Verantwortliche Stelle
Verantwortliche Stelle für die Erhebung, Verarbeitung und Nutzung deier personenbezogenen Daten im Sinne des Bundesdatenschutzgesetzes ist die Initiative wepublic, wie im Impressum angegeben. Sofern du der Erhebung, Verarbeitung oder Nutzung deiner Daten durch wepublic nach Maßgabe dieser Datenschutzbestimmungen insgesamt oder für einzelne Maßnahmen widersprechen willst, kannst du deinen Widerspruch per E-Mail oder Brief an folgende Kontaktdaten senden: Simon Gogolin, Adriana Groh, Julia Riederer, Cornelia Kolb, Alex Bär, Marius Schulz, Tim Zeidler, GbR: Schloßstraße 96, 60486 Frankfurt/M; Mobil: 0176-82979447; E-Mail: hello@wepublic.me.
Personenbezogene Daten
Personenbezogene Daten sind Einzelangaben über sachliche oder persönliche Verhältnisse einer bestimmten oder bestimmbaren natürlichen Person. Unser Ziel ist es so wenig wie möglich personenbezogene Daten zu erheben, zu verarbeiten und zu nutzen.
Wir bieten bieten nach Registrierung einen individuellen, direkten und passwortgeschützen Zugang zu unserer App +me. Du verpflichtest dich, die persönlichen Zugangsdaten vertraulich zu behandeln und keinem unbefugten Dritten zugänglich zu machen. Wepublic kann keine Haftung für missbräuchlich verwendete Passwörter übernehmen, es sei denn, der Missbrauch ist von uns zu vertreten. Sofern du dich nicht abmeldest, bleibst du automatisch eingeloggt. Diese Funktion ermöglicht dir die Nutzung eines Teils unserer Dienste ohne dich jedes Mal erneut einloggen zu müssen. Aus Sicherheitsgründen könntest du jedoch nochmals zur Eingabe deines Passworts aufgefordert werden.
Deine personenbezogenen Daten werden ohne deine ausdrückliche Zustimmung nicht an Dritte weitergegeben. Deine E-Mail-Adresse benötigen wir, damit wir mit dir kommunizieren können. Wir nutzen diese zudem für deine Identifikation für die Benutzung unserer App +me. Eine Löschung deiner personenbezogenen Daten erfolgt, sofern gesetzliche Aufbewahrungspflichten dem nicht entgegenstehen und du einen Löschungsanspruch geltend gemacht hast, wenn die Daten zur Erfüllung des mit der Speicherung verfolgten Zwecks nicht mehr erforderlich sind oder wenn deine Speicherung aus sonstigen gesetzlichen Gründen unzulässig ist.

22.08.2017

**Comment by CameliaKollo** [comment]
Datenschutzrichtlinie im Menü anlegen, damit man immer Zugriff hat

und wichtig mit Datum versehen unter dem Text.

**Comment by Bartz0210** [comment]
Ich werde auf die gleiche Seite beim Android-Testen geleitet, mit der Nachricht "Password is too common", wenn ich als PW "12345678" verwende.
Bei meinem Testpasswort "Penny1" wird mir gesagt ich solle ein Passwort mit 6 Zeichen verwenden, obwohl ich das tue.

**Comment by ThyMYthOS** [comment]
Welche Seite ist denn "die gleiche"?
Das Passwort muss 8 Zeichen haben, da ist der Hinweistext noch falsch.
