### ISSUE TITLE
Anmeldung Android

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#38]
(Android) Wenn man bereits angemeldet war, die App aber neu startet, wird beim Start zuerst kurz der Konto-anlegen/einloggen Screen angezeigt, bevor man dann kurz drauf automatisch angemeldet wird.
Wie problematisch ist das @Bartz0210 bzw. tritt das bei dir auch auf?

**Comment by ThyMYthOS** [comment]
Evtl. kann ich den Splashscreen etwas länger offen lassen.
