### ISSUE TITLE
Onboarding erscheint nach erneutem Login kurz

### ISSUE THREAD

**Issue by Bartz0210** [wepublic/ionic-app#40]
Der erste Onboarding Screen ist kurz sichtbar, wenn man sich nach eine Logout wieder anmeldet

**Comment by CameliaKollo** [comment]
Onboarding Text hat noch Rechtschreibfehler. Bitte folgende Texte einbinden:

Fragen folgen mit Wisch-Geste.
Swipe nach rechts zu +me, wenn dich eine Frage interessiert. Je mehr +me Votes, desto schneller wird die Frage von den Politikern beantwortet. 

Eigene Fragen stellen.
Hast du genügend Fragen bewertet, kannst du selber Fragen stellen! Erhalten deine Fragen viele +me Votes gehen sie direkt an alle Kandidaten. 

Antworten bekommen und bewerten.
Lies die Antworten der Kandidaten und bewerte sie mit einer Wisch-Geste. Danach erfährst du von wem die Antwort ist. 

Und hier unten geht es los!
Entdecke und bewerte Fragen der Community. Oder suche gezielt nach Fragen zu Themen, die dich interessieren.
