### ISSUE TITLE
Frage stellen: Tags auf 3 begrenzen und Form der Bubble

### ISSUE THREAD

**Issue by Bartz0210** [wepublic/ionic-app#44]
Der Bubble fehlt noch ein Schwänzchen
![screenshot_2017-08-22-17-15-58](https://user-images.githubusercontent.com/26096685/29580102-21f6c910-8775-11e7-98c5-028f49f59003.png)

**Comment by ThyMYthOS** [comment]
Fixed in b3246a993075
