### ISSUE TITLE
Navigation-Bar, Icon-Farbe

### ISSUE THREAD

**Issue by simongogolin** [wepublic/ionic-app#49]
@ThyMYthOS – Das hat keine Top Priorität, ist nur ein nice to have, wenn es deine Zeit am Ende noch erlaubt:

1. Die Icons und die Beschriftung der Navigation-Bar haben (unter iOS) gerade ein relativ helles grau, was die Lesbarkeit beeeinträchtigt. Könntest du die Farben der Icons + Schrift auf HEX: 616161 ändern?

2. Beim jeweils angewählten Icon wird derzeit auch die Bechriftung grün – das lässt sich leider auch schlecht lesen. Kannst du die Schrift hier auf HEX: 29c49a stellen? Das sollte dem Problem schonmal etwas entgegenwirken.

**Comment by ThyMYthOS** [comment]
Leider kann man in der Ionic-Tabbar nur echte Icons setzen, keine beliebigen SVGs. Die Icons können nur monochrom sein und Ionic kann die Farbe dann automatisch anpassen (aktiv, inaktiv). Siehe auch https://ionicframework.com/docs/api/components/tabs/Tab/
