### ISSUE TITLE
Register Users not working

### ISSUE THREAD

**Issue by mrWinston** [wepublic/ionic-app#5]
The Format of the json is incorrect when posting the new user data. This is sent:
```
{
       'birthYear': '1990', 
       'email': 'marius@test.de', 
       'sex': 'm', 
       'plz': '13', 
       'password': 'password'
}
```

And this would be the correct format:
```
{
	"email": "marius@test.de",
	"password": "password",
	"username": "user",
	"zip_code": "13",
        "gender": "m",
        "year_of_birth": 1990
	"first_name": "Jana"
}
```

see the backend docs for details.

**Comment by ThyMYthOS** [comment]
Do we really need a Username?

**Comment by mrWinston** [comment]
I don't really know anymore. Currently, it's mandatory. The idea was to have some name for emails to the user. But it's not necessary. 
I think we should discuss this with the others on slack. 
My workaround currently consists of using the email until the @ as the username.

**Comment by AVWG** [comment]
Email until the @-sign works as username. We could also abandon everything and just go with the email address for signing in.

**Comment by ThyMYthOS** [comment]
Bug closed for now. New feature request should be opened if changes are required.
