### ISSUE TITLE
Login after registration

### ISSUE THREAD

**Issue by mrWinston** [wepublic/ionic-app#52]
It would be nice, if the user wouldn't have to type in his email and password right after registration. 
After signing up, the backend sends back the api token of the new user. If the app then tries to access the api with that token, it returns:
```
CODE 401 Unauthorized
{
    "detail": "User inactive or deleted."
}
```
until the user has confirmed the email address. The frontend could just try to load /Users/me when the app is opened to see, weather the address is verified. 

although, there might be some security implications i'm not seeing.

**Comment by ThyMYthOS** [comment]
Wenn man erst den Bestätigungslink öffnet und dann auf "Verstanden" in der App klickt funktioniert es.
