### ISSUE TITLE
My questions

### ISSUE THREAD

**Issue by CameliaKollo** [wepublic/ionic-app#56]
Always shows a total number of 1 or 0 as the total amount of votes

**Comment by ThyMYthOS** [comment]
Wenn du die Frage positiv bewertet hast, bedeutet die Anzahl x + me. 0
bedeutet also, dass die Frage sonst noch niemand positiv bewertet hat.

**Comment by CameliaKollo** [comment]
Ok, mich hat nur gewundert, dass das so wenige waren nach den Tests. Wollte nur sicher gehen :) danke
