### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by CameliaKollo** [wepublic/ionic-app#57]
Under contact the following text is not needed: 
Folgt uns auf Facebook, Twitter

support@wepublic.me is missing for technical issues?

Is it possible to get a back-button from the menu if I decide not to check any of the topics offered. Clicking on the three lines (menu-button) is not working easily or intuitive.

**Comment by ThyMYthOS** [comment]
> Is it possible to get a back-button from the menu if I decide not to check any of the topics offered. Clicking on the three lines (menu-button) is not working easily or intuitive. 

Do you mean for iOS? In Android the back button works perfectly to close the menu.
