### ISSUE TITLE
Top questions

### ISSUE THREAD

**Issue by CameliaKollo** [wepublic/ionic-app#62]
Rate all questions on basis of highest votes in the community, regardless of the own interest. 
If not any hashtag was chosen, questions should be shown in the rank of votes in the community, regardless of the topic they were attached to.

**Comment by ThyMYthOS** [comment]
Needs https://github.com/wepublic/backend/issues/65

**Comment by CameliaKollo** [comment]
Without hashtags used all questions I see r grey as if I didn't support them. When I use hashtags the same question is green and shows that I liked it.
