### ISSUE TITLE
Increment Vote Count after voting up

### ISSUE THREAD

**Issue by mrWinston** [wepublic/ionic-app#66]
When a question is voted up, the vote count doesn't increase immediately. 
This would be nice feedback for the user. 
You could either just add one to the vote count, or show the value from the returned question object. 

POST /v1/Questions/<pk>/upvote returns the question with the updated upvote count.

**Comment by ThyMYthOS** [comment]
Acually I do increment the vote count, but when the count is shown above the +me icon I always reduce it by one. So if you post a question yourself you will see 0+me on that question. Others will see 1 on the community icon.

I think this is pretty logical.
