### ISSUE TITLE
Report button

### ISSUE THREAD

**Issue by AVWG** [wepublic/ionic-app#7]
We need a report function. This means that user could report questions and make them temporarily invisible, until an admin checked an reactivated or deleted the questions.

**Comment by Bartz0210** [comment]
Is this done?
In our screendesign we already ahve the link/button and the screen, describing how it should work.

**Comment by ThyMYthOS** [comment]
Backend support is still missing.

Tim Zeidler <notifications@github.com> schrieb am Do., 10. Aug. 2017, 20:19:

**Comment by SayAntiAnti** [comment]
Braucht ihr dafür noch etwas von unserer Seite?
