### ISSUE TITLE
hashtags

### ISSUE THREAD

**Issue by CameliaKollo** [wepublic/ionic-app#8]
new screendesign for hashtag selection from simon 
hashtags are pre-defined and cannot be created by the user

**Comment by ThyMYthOS** [comment]
So what exactly needs to be changed in the app?

**Comment by CameliaKollo** [comment]
Simon is preparing the new screendesign which will explain what we need. Did u get this already?

**Comment by ThyMYthOS** [comment]
No, not yet.

**Comment by CameliaKollo** [comment]
I think Simon is happy with the solution you already implemented. So its done :)
